apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: enterprise-apps
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Mypa$$word@456"
  MYSQL_DATABASE: "employees"
  MYSQL_USER: "ems_user"
  MYSQL_PASSWORD: "EmployeePass123!"