from enum import Enum

class ErrorCode(str, Enum):
    INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    UNAUTHORIZED = "UNAUTHORIZED"
    
    EMPLOYEE_NOT_FOUND = "EMPLOYEE_NOT_FOUND"
    DUPLICATE_EMAIL = "EMPLOYEE_DUPLICATE_EMAIL"
    
    DATABASE_ERROR = "SYS_DATABASE_ERROR"
    INTERNAL_ERROR = "SYS_INTERNAL_ERROR"
    VALIDATION_ERROR = "SYS_VALIDATION_ERROR"
    
    CRYPTO_FAILURE = "PASSWORD_HASHING_ERROR"
    VERIFICATION_FAILURE ="PASSWORD_NOT_VERIFIED"
    