apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: enterprise-apps
type: Opaque
stringData:
  SECRET_KEY: "saUlSDXDes4EpWrl67MA3.wtsGwVo8ZF/hjVbrLOMpN39u2MNc/Y."
  DB_PASSWORD: "EmployeePass123!"